export {
  bindKeysFromRaw,
  displayDoesForLang,
  displayLabelForLang,
  exactMatchFromRaw,
  examplesFromRaw,
  hasValueIrisFromRaw,
  isDefinedByFromRaw,
  kindSpecificTitle,
  languageDisplayName,
  multilangFromRaw,
  poleFromChain,
  provenanceFromRaw,
  providesFunctionIrisFromRaw,
  sanskritFromRaw,
  valuePlanguageFromRaw,
  verbFromRaw,
  type MultilangView,
  type OntologyKind,
  type SanskritView,
  type TermLabelDoc,
  type ValueMeterView,
  type ValuePlanguageView,
} from "./termView";
